# Generated by Django 4.1.1 on 2022-10-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.FloatField(blank=True, null=True)),
                ('var2', models.CharField(blank=True, max_length=2, null=True)),
                ('var3', models.FloatField(blank=True, null=True)),
                ('var4', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
